//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using Zyh.Common.Service.Base;


namespace Zyh.Common.Service
{
    
    
    public partial class LedEquipSqlService : LedEquipSqlServiceBase
    {
        
        const String DefaultConnectionString = "DefaultConnectionString";
        
        public LedEquipSqlService() : 
                this(DefaultConnectionString)
        {
        }
        
        public LedEquipSqlService(string connectionName) : 
                base(connectionName)
        {
        }
    }
}
