//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using Zyh.Common.Entity;
using Zyh.Common.Provider.Base;


namespace Zyh.Common.Provider
{
    
    
    public partial class LedEquipSqlProvider : LedEquipSqlProviderBase
    {
        
        public LedEquipSqlProvider() : 
                base()
        {
        }
        
        public LedEquipSqlProvider(string connectionName) : 
                base(connectionName)
        {
        }
    }
}
